var _i_hash_function___extensions___tests_8cs =
[
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests" ],
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests.Sugar", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar" ],
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests.SugarWithDesiredSize", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar_with_desired_size.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar_with_desired_size" ]
];