var _modified_bernstein_hash_factory___tests_8cs =
[
    [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash_factory___tests.html", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash_factory___tests" ]
];