var _modified_bernstein_hash___implementation___tests_8cs =
[
    [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation___tests.html", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation___tests" ],
    [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHash_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implement5faf157baec7e0c60cad2009329a3807.html", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implement5faf157baec7e0c60cad2009329a3807" ]
];