var hierarchy =
[
    [ "AutoGeneratedProgram", "class_auto_generated_program.html", null ],
    [ "Data.HashFunction.Test.BernsteinHash.BernsteinHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_bernstein_hash___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.BernsteinHash.BernsteinHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_bernstein_hash_factory___tests.html", null ],
    [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Blake2.Blake2BConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b_config___tests.html", null ],
    [ "Data.HashFunction.Test.Blake2.Blake2BFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b_factory___tests.html", null ],
    [ "Data.HashFunction.Test.Blake3.Blake3_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake3_1_1_blake3___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Blake3.Blake3Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake3_1_1_blake3_config___tests.html", null ],
    [ "Data.HashFunction.Test.Blake3.Blake3Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake3_1_1_blake3_factory___tests.html", null ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.BernsteinHash.BernsteinHash_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_bernstein_hash___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.BernsteinHash.ModifiedBernsteinHash_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.Blake2.Blake2B_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_blake2_1_1_blake2_b___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.CRC.CRC_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_c_r_c_1_1_c_r_c___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.ELF64.ELF64_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_e_l_f64_1_1_e_l_f64___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.Jenkins.JenkinsLookup2_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup2___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.Jenkins.JenkinsOneAtATime_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_one_at_a_time___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.MetroHash.MetroHash128_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash128___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.MetroHash.MetroHash64_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash64___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.Pearson.Pearson_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_pearson_1_1_pearson___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.SpookyHash.SpookyHashV1_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v1___implementation_1_1_block_transformer.html", null ],
      [ "Data.HashFunction.SpookyHash.SpookyHashV2_Implementation.BlockTransformer", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v2___implementation_1_1_block_transformer.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer128 >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash3_Implementation.BlockTransformer128", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3___implementation_1_1_block_transformer128.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer32 >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash3_Implementation.BlockTransformer32", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3___implementation_1_1_block_transformer32.html", null ],
      [ "Data.HashFunction.xxHash.xxHash_Implementation.BlockTransformer32", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash___implementation_1_1_block_transformer32.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer64 >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.xxHash.xxHash_Implementation.BlockTransformer64", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash___implementation_1_1_block_transformer64.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer_16Bit >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.BuzHash.BuzHash_Implementation.BlockTransformer_16Bit", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation_1_1_block_transformer__16_bit.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer_32Bit >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.BuzHash.BuzHash_Implementation.BlockTransformer_32Bit", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation_1_1_block_transformer__32_bit.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer_64Bit >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.BuzHash.BuzHash_Implementation.BlockTransformer_64Bit", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation_1_1_block_transformer__64_bit.html", null ]
    ] ],
    [ "Data.HashFunction.Core.BlockTransformerBase< BlockTransformer_8Bit >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
      [ "Data.HashFunction.BuzHash.BuzHash_Implementation.BlockTransformer_8Bit", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation_1_1_block_transformer__8_bit.html", null ]
    ] ],
    [ "Data.HashFunction.Test.BuzHash.BuzHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.BuzHash.BuzHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.BuzHash.BuzHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash_factory___tests.html", null ],
    [ "Data.HashFunction.Test.CityHash.CityHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_city_hash___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.CityHash.CityHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_city_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.CityHash.CityHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_city_hash_factory___tests.html", null ],
    [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.CRC.CRCConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c_config___tests.html", null ],
    [ "Data.HashFunction.Test.CRC.CRCFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c_factory___tests.html", null ],
    [ "Data.HashFunction.Test.BuzHash.DefaultBuzHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_default_buz_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.ELF64.ELF64_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_e_l_f64_1_1_e_l_f64___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.ELF64.ELF64Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_e_l_f64_1_1_e_l_f64_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint128_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint128___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint128Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint128_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint32_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint32___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint32Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint32_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint64_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint64___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint64Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint64_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNV1_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNV1a_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1a___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNV1aFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1a_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNV1Base_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1_base___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNV1Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1_factory___tests.html", null ],
    [ "Data.HashFunction.Test.FNV.FNVConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v_config___tests.html", null ],
    [ "Data.HashFunction.FNV.Utilities.FNVPrimeOffset", "class_data_1_1_hash_function_1_1_f_n_v_1_1_utilities_1_1_f_n_v_prime_offset.html", null ],
    [ "Data.HashFunction.Test.FNV.Utilities.FNVPrimeOffset_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_utilities_1_1_f_n_v_prime_offset___tests.html", null ],
    [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapperConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper_config___tests.html", null ],
    [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapperFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper_factory___tests.html", null ],
    [ "Data.HashFunction.Test.Core.HashFunctionBase_Tests", "class_data_1_1_hash_function_1_1_test_1_1_core_1_1_hash_function_base___tests.html", null ],
    [ "Data.HashFunction.Test.Core.Utilities.HashValue_Tests", "class_data_1_1_hash_function_1_1_test_1_1_core_1_1_utilities_1_1_hash_value___tests.html", null ],
    [ "Data.HashFunction.BernsteinHash.IBernsteinHashFactory", "interface_data_1_1_hash_function_1_1_bernstein_hash_1_1_i_bernstein_hash_factory.html", [
      [ "Data.HashFunction.BernsteinHash.BernsteinHashFactory", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_bernstein_hash_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Blake2.IBlake2BConfig", "interface_data_1_1_hash_function_1_1_blake2_1_1_i_blake2_b_config.html", [
      [ "Data.HashFunction.Blake2.Blake2BConfig", "class_data_1_1_hash_function_1_1_blake2_1_1_blake2_b_config.html", null ]
    ] ],
    [ "Data.HashFunction.Blake2.IBlake2BFactory", "interface_data_1_1_hash_function_1_1_blake2_1_1_i_blake2_b_factory.html", [
      [ "Data.HashFunction.Blake2.Blake2BFactory", "class_data_1_1_hash_function_1_1_blake2_1_1_blake2_b_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Blake3.IBlake3Config", "interface_data_1_1_hash_function_1_1_blake3_1_1_i_blake3_config.html", [
      [ "Data.HashFunction.Blake3.Blake3Config", "class_data_1_1_hash_function_1_1_blake3_1_1_blake3_config.html", null ]
    ] ],
    [ "Data.HashFunction.Blake3.IBlake3Factory", "interface_data_1_1_hash_function_1_1_blake3_1_1_i_blake3_factory.html", [
      [ "Data.HashFunction.Blake3.Blake3Factory", "class_data_1_1_hash_function_1_1_blake3_1_1_blake3_factory.html", null ]
    ] ],
    [ "Data.HashFunction.IBlockTransformer", "interface_data_1_1_hash_function_1_1_i_block_transformer.html", [
      [ "Data.HashFunction.Core.BlockTransformerBase< TSelf >", "class_data_1_1_hash_function_1_1_core_1_1_block_transformer_base.html", [
        [ "Data.HashFunction.FNV.FNV1Base.BlockTransformer_32BitBase< TSelf >", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_base_1_1_block_transformer__32_bit_base.html", [
          [ "Data.HashFunction.FNV.FNV1_Implementation.BlockTransformer_32Bit", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1___implementation_1_1_block_transformer__32_bit.html", null ],
          [ "Data.HashFunction.FNV.FNV1a_Implementation.BlockTransformer_32Bit", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a___implementation_1_1_block_transformer__32_bit.html", null ]
        ] ],
        [ "Data.HashFunction.FNV.FNV1Base.BlockTransformer_64BitBase< TSelf >", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_base_1_1_block_transformer__64_bit_base.html", [
          [ "Data.HashFunction.FNV.FNV1_Implementation.BlockTransformer_64Bit", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1___implementation_1_1_block_transformer__64_bit.html", null ],
          [ "Data.HashFunction.FNV.FNV1a_Implementation.BlockTransformer_64Bit", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a___implementation_1_1_block_transformer__64_bit.html", null ]
        ] ],
        [ "Data.HashFunction.FNV.FNV1Base.BlockTransformer_ExtendedBase< TSelf >", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_base_1_1_block_transformer___extended_base.html", [
          [ "Data.HashFunction.FNV.FNV1_Implementation.BlockTransformer_Extended", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1___implementation_1_1_block_transformer___extended.html", null ],
          [ "Data.HashFunction.FNV.FNV1a_Implementation.BlockTransformer_Extended", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a___implementation_1_1_block_transformer___extended.html", null ]
        ] ]
      ] ]
    ] ],
    [ "Data.HashFunction.BuzHash.IBuzHashConfig", "interface_data_1_1_hash_function_1_1_buz_hash_1_1_i_buz_hash_config.html", [
      [ "Data.HashFunction.BuzHash.BuzHashConfig", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash_config.html", null ],
      [ "Data.HashFunction.BuzHash.DefaultBuzHashConfig", "class_data_1_1_hash_function_1_1_buz_hash_1_1_default_buz_hash_config.html", null ]
    ] ],
    [ "Data.HashFunction.BuzHash.IBuzHashFactory", "interface_data_1_1_hash_function_1_1_buz_hash_1_1_i_buz_hash_factory.html", [
      [ "Data.HashFunction.BuzHash.BuzHashFactory", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash_factory.html", null ]
    ] ],
    [ "Data.HashFunction.CityHash.ICityHashConfig", "interface_data_1_1_hash_function_1_1_city_hash_1_1_i_city_hash_config.html", [
      [ "Data.HashFunction.CityHash.CityHashConfig", "class_data_1_1_hash_function_1_1_city_hash_1_1_city_hash_config.html", null ]
    ] ],
    [ "Data.HashFunction.CityHash.ICityHashFactory", "interface_data_1_1_hash_function_1_1_city_hash_1_1_i_city_hash_factory.html", [
      [ "Data.HashFunction.CityHash.CityHashFactory", "class_data_1_1_hash_function_1_1_city_hash_1_1_city_hash_factory.html", null ]
    ] ],
    [ "Data.HashFunction.CRC.ICRCConfig", "interface_data_1_1_hash_function_1_1_c_r_c_1_1_i_c_r_c_config.html", [
      [ "Data.HashFunction.CRC.CRCConfig", "class_data_1_1_hash_function_1_1_c_r_c_1_1_c_r_c_config.html", null ]
    ] ],
    [ "Data.HashFunction.CRC.ICRCFactory", "interface_data_1_1_hash_function_1_1_c_r_c_1_1_i_c_r_c_factory.html", [
      [ "Data.HashFunction.CRC.CRCFactory", "class_data_1_1_hash_function_1_1_c_r_c_1_1_c_r_c_factory.html", null ]
    ] ],
    [ "IDisposable", null, [
      [ "Data.HashFunction.Blake3.Hasher", "class_data_1_1_hash_function_1_1_blake3_1_1_hasher.html", null ],
      [ "Data.HashFunction.Core.LibraryLoader.NativeLibraryLoader", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_native_library_loader.html", [
        [ "Data.HashFunction.Core.LibraryLoader.NativeLibraryLoader.UnixNativeLibrary", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_native_library_loader_1_1_unix_native_library.html", null ],
        [ "Data.HashFunction.Core.LibraryLoader.NativeLibraryLoader.WindowsNativeLibrary", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_native_library_loader_1_1_windows_native_library.html", null ]
      ] ]
    ] ],
    [ "Data.HashFunction.ELF64.IELF64Factory", "interface_data_1_1_hash_function_1_1_e_l_f64_1_1_i_e_l_f64_factory.html", [
      [ "Data.HashFunction.ELF64.ELF64Factory", "class_data_1_1_hash_function_1_1_e_l_f64_1_1_e_l_f64_factory.html", null ]
    ] ],
    [ "IEquatable", null, [
      [ "Data.HashFunction.IHashValue", "interface_data_1_1_hash_function_1_1_i_hash_value.html", [
        [ "Data.HashFunction.Core.Utilities.HashValue", "class_data_1_1_hash_function_1_1_core_1_1_utilities_1_1_hash_value.html", null ]
      ] ]
    ] ],
    [ "Data.HashFunction.FarmHash.IFarmHashFingerprint128Factory", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint128_factory.html", [
      [ "Data.HashFunction.FarmHash.FarmHashFingerprint128Factory", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint128_factory.html", null ]
    ] ],
    [ "Data.HashFunction.FarmHash.IFarmHashFingerprint32Factory", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint32_factory.html", [
      [ "Data.HashFunction.FarmHash.FarmHashFingerprint32Factory", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint32_factory.html", null ]
    ] ],
    [ "Data.HashFunction.FarmHash.IFarmHashFingerprint64Factory", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint64_factory.html", [
      [ "Data.HashFunction.FarmHash.FarmHashFingerprint64Factory", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint64_factory.html", null ]
    ] ],
    [ "Data.HashFunction.FNV.IFNV1aFactory", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v1a_factory.html", [
      [ "Data.HashFunction.FNV.FNV1aFactory", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a_factory.html", null ]
    ] ],
    [ "Data.HashFunction.FNV.IFNV1Factory", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v1_factory.html", [
      [ "Data.HashFunction.FNV.FNV1Factory", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_factory.html", null ]
    ] ],
    [ "Data.HashFunction.FNV.IFNVConfig", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v_config.html", [
      [ "Data.HashFunction.FNV.FNVConfig", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v_config.html", null ]
    ] ],
    [ "Data.HashFunction.HashAlgorithm.IHashAlgorithmWrapperConfig", "interface_data_1_1_hash_function_1_1_hash_algorithm_1_1_i_hash_algorithm_wrapper_config.html", [
      [ "Data.HashFunction.HashAlgorithm.HashAlgorithmWrapperConfig", "class_data_1_1_hash_function_1_1_hash_algorithm_1_1_hash_algorithm_wrapper_config.html", null ]
    ] ],
    [ "Data.HashFunction.HashAlgorithm.IHashAlgorithmWrapperFactory", "interface_data_1_1_hash_function_1_1_hash_algorithm_1_1_i_hash_algorithm_wrapper_factory.html", [
      [ "Data.HashFunction.HashAlgorithm.HashAlgorithmWrapperFactory", "class_data_1_1_hash_function_1_1_hash_algorithm_1_1_hash_algorithm_wrapper_factory.html", null ]
    ] ],
    [ "Data.HashFunction.IHashFunction", "interface_data_1_1_hash_function_1_1_i_hash_function.html", [
      [ "Data.HashFunction.Blake3.IBlake3", "interface_data_1_1_hash_function_1_1_blake3_1_1_i_blake3.html", [
        [ "Data.HashFunction.Blake3.Blake3_Implementation", "class_data_1_1_hash_function_1_1_blake3_1_1_blake3___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.CityHash.ICityHash", "interface_data_1_1_hash_function_1_1_city_hash_1_1_i_city_hash.html", [
        [ "Data.HashFunction.CityHash.CityHash_Implementation", "class_data_1_1_hash_function_1_1_city_hash_1_1_city_hash___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.Core.HashFunctionBase", "class_data_1_1_hash_function_1_1_core_1_1_hash_function_base.html", [
        [ "Data.HashFunction.Blake3.Blake3_Implementation", "class_data_1_1_hash_function_1_1_blake3_1_1_blake3___implementation.html", null ],
        [ "Data.HashFunction.CityHash.CityHash_Implementation", "class_data_1_1_hash_function_1_1_city_hash_1_1_city_hash___implementation.html", null ],
        [ "Data.HashFunction.Core.StreamableHashFunctionBase", "class_data_1_1_hash_function_1_1_core_1_1_streamable_hash_function_base.html", [
          [ "Data.HashFunction.BernsteinHash.BernsteinHash_Implementation", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_bernstein_hash___implementation.html", null ],
          [ "Data.HashFunction.BernsteinHash.ModifiedBernsteinHash_Implementation", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation.html", null ],
          [ "Data.HashFunction.Blake2.Blake2B_Implementation", "class_data_1_1_hash_function_1_1_blake2_1_1_blake2_b___implementation.html", null ],
          [ "Data.HashFunction.BuzHash.BuzHash_Implementation", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation.html", null ],
          [ "Data.HashFunction.CRC.CRC_Implementation", "class_data_1_1_hash_function_1_1_c_r_c_1_1_c_r_c___implementation.html", null ],
          [ "Data.HashFunction.ELF64.ELF64_Implementation", "class_data_1_1_hash_function_1_1_e_l_f64_1_1_e_l_f64___implementation.html", null ],
          [ "Data.HashFunction.FNV.FNV1Base", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_base.html", [
            [ "Data.HashFunction.FNV.FNV1_Implementation", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1___implementation.html", null ],
            [ "Data.HashFunction.FNV.FNV1a_Implementation", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a___implementation.html", null ],
            [ "Data.HashFunction.Test.FNV.FNV1Base_Tests.FNV1Impl", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1_base___tests_1_1_f_n_v1_impl.html", null ]
          ] ],
          [ "Data.HashFunction.Jenkins.JenkinsLookup2_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup2___implementation.html", null ],
          [ "Data.HashFunction.Jenkins.JenkinsOneAtATime_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_one_at_a_time___implementation.html", null ],
          [ "Data.HashFunction.MetroHash.MetroHash128_Implementation", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash128___implementation.html", null ],
          [ "Data.HashFunction.MetroHash.MetroHash64_Implementation", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash64___implementation.html", null ],
          [ "Data.HashFunction.MurmurHash.MurmurHash3_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3___implementation.html", null ],
          [ "Data.HashFunction.Pearson.Pearson_Implementation", "class_data_1_1_hash_function_1_1_pearson_1_1_pearson___implementation.html", null ],
          [ "Data.HashFunction.SpookyHash.SpookyHashV1_Implementation", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v1___implementation.html", null ],
          [ "Data.HashFunction.SpookyHash.SpookyHashV2_Implementation", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v2___implementation.html", null ],
          [ "Data.HashFunction.xxHash.xxHash_Implementation", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint128_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint128___implementation.html", null ],
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint32_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint32___implementation.html", null ],
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint64_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint64___implementation.html", null ],
        [ "Data.HashFunction.HashAlgorithm.HashAlgorithmWrapper_Implementation", "class_data_1_1_hash_function_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementation.html", null ],
        [ "Data.HashFunction.Jenkins.JenkinsLookup3_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup3___implementation.html", null ],
        [ "Data.HashFunction.MurmurHash.MurmurHash1_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash1___implementation.html", null ],
        [ "Data.HashFunction.MurmurHash.MurmurHash2_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash2___implementation.html", null ],
        [ "Data.HashFunction.Test._Mocks.HashFunctionImpl", "class_data_1_1_hash_function_1_1_test_1_1___mocks_1_1_hash_function_impl.html", null ]
      ] ],
      [ "Data.HashFunction.FarmHash.IFarmHashFingerprint128", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint128.html", [
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint128_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint128___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.FarmHash.IFarmHashFingerprint32", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint32.html", [
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint32_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint32___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.FarmHash.IFarmHashFingerprint64", "interface_data_1_1_hash_function_1_1_farm_hash_1_1_i_farm_hash_fingerprint64.html", [
        [ "Data.HashFunction.FarmHash.FarmHashFingerprint64_Implementation", "class_data_1_1_hash_function_1_1_farm_hash_1_1_farm_hash_fingerprint64___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.HashAlgorithm.IHashAlgorithmWrapper", "interface_data_1_1_hash_function_1_1_hash_algorithm_1_1_i_hash_algorithm_wrapper.html", [
        [ "Data.HashFunction.HashAlgorithm.HashAlgorithmWrapper_Implementation", "class_data_1_1_hash_function_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.IStreamableHashFunction", "interface_data_1_1_hash_function_1_1_i_streamable_hash_function.html", [
        [ "Data.HashFunction.BernsteinHash.IBernsteinHash", "interface_data_1_1_hash_function_1_1_bernstein_hash_1_1_i_bernstein_hash.html", [
          [ "Data.HashFunction.BernsteinHash.BernsteinHash_Implementation", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_bernstein_hash___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.BernsteinHash.IModifiedBernsteinHash", "interface_data_1_1_hash_function_1_1_bernstein_hash_1_1_i_modified_bernstein_hash.html", [
          [ "Data.HashFunction.BernsteinHash.ModifiedBernsteinHash_Implementation", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.Blake2.IBlake2B", "interface_data_1_1_hash_function_1_1_blake2_1_1_i_blake2_b.html", [
          [ "Data.HashFunction.Blake2.Blake2B_Implementation", "class_data_1_1_hash_function_1_1_blake2_1_1_blake2_b___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.BuzHash.IBuzHash", "interface_data_1_1_hash_function_1_1_buz_hash_1_1_i_buz_hash.html", [
          [ "Data.HashFunction.BuzHash.BuzHash_Implementation", "class_data_1_1_hash_function_1_1_buz_hash_1_1_buz_hash___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.CRC.ICRC", "interface_data_1_1_hash_function_1_1_c_r_c_1_1_i_c_r_c.html", [
          [ "Data.HashFunction.CRC.CRC_Implementation", "class_data_1_1_hash_function_1_1_c_r_c_1_1_c_r_c___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.Core.StreamableHashFunctionBase", "class_data_1_1_hash_function_1_1_core_1_1_streamable_hash_function_base.html", null ],
        [ "Data.HashFunction.ELF64.IELF64", "interface_data_1_1_hash_function_1_1_e_l_f64_1_1_i_e_l_f64.html", [
          [ "Data.HashFunction.ELF64.ELF64_Implementation", "class_data_1_1_hash_function_1_1_e_l_f64_1_1_e_l_f64___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.FNV.IFNV", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v.html", [
          [ "Data.HashFunction.FNV.FNV1Base", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1_base.html", null ],
          [ "Data.HashFunction.FNV.IFNV1", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v1.html", [
            [ "Data.HashFunction.FNV.FNV1_Implementation", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1___implementation.html", null ]
          ] ],
          [ "Data.HashFunction.FNV.IFNV1a", "interface_data_1_1_hash_function_1_1_f_n_v_1_1_i_f_n_v1a.html", [
            [ "Data.HashFunction.FNV.FNV1a_Implementation", "class_data_1_1_hash_function_1_1_f_n_v_1_1_f_n_v1a___implementation.html", null ]
          ] ]
        ] ],
        [ "Data.HashFunction.Jenkins.IJenkins", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins.html", [
          [ "Data.HashFunction.Jenkins.IJenkinsLookup2", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup2.html", [
            [ "Data.HashFunction.Jenkins.JenkinsLookup2_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup2___implementation.html", null ]
          ] ],
          [ "Data.HashFunction.Jenkins.IJenkinsOneAtATime", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_one_at_a_time.html", [
            [ "Data.HashFunction.Jenkins.JenkinsOneAtATime_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_one_at_a_time___implementation.html", null ]
          ] ]
        ] ],
        [ "Data.HashFunction.MetroHash.IMetroHash128", "interface_data_1_1_hash_function_1_1_metro_hash_1_1_i_metro_hash128.html", [
          [ "Data.HashFunction.MetroHash.MetroHash128_Implementation", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash128___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.MetroHash.IMetroHash64", "interface_data_1_1_hash_function_1_1_metro_hash_1_1_i_metro_hash64.html", [
          [ "Data.HashFunction.MetroHash.MetroHash64_Implementation", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash64___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.MurmurHash.IMurmurHash3", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash3.html", [
          [ "Data.HashFunction.MurmurHash.MurmurHash3_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.Pearson.IPearson", "interface_data_1_1_hash_function_1_1_pearson_1_1_i_pearson.html", [
          [ "Data.HashFunction.Pearson.Pearson_Implementation", "class_data_1_1_hash_function_1_1_pearson_1_1_pearson___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.SpookyHash.ISpookyHashV1", "interface_data_1_1_hash_function_1_1_spooky_hash_1_1_i_spooky_hash_v1.html", [
          [ "Data.HashFunction.SpookyHash.SpookyHashV1_Implementation", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v1___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.SpookyHash.ISpookyHashV2", "interface_data_1_1_hash_function_1_1_spooky_hash_1_1_i_spooky_hash_v2.html", [
          [ "Data.HashFunction.SpookyHash.SpookyHashV2_Implementation", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v2___implementation.html", null ]
        ] ],
        [ "Data.HashFunction.xxHash.IxxHash", "interface_data_1_1_hash_function_1_1xx_hash_1_1_ixx_hash.html", [
          [ "Data.HashFunction.xxHash.xxHash_Implementation", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash___implementation.html", null ]
        ] ]
      ] ],
      [ "Data.HashFunction.Jenkins.IJenkinsLookup3", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup3.html", [
        [ "Data.HashFunction.Jenkins.JenkinsLookup3_Implementation", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup3___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.MurmurHash.IMurmurHash1", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash1.html", [
        [ "Data.HashFunction.MurmurHash.MurmurHash1_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash1___implementation.html", null ]
      ] ],
      [ "Data.HashFunction.MurmurHash.IMurmurHash2", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash2.html", [
        [ "Data.HashFunction.MurmurHash.MurmurHash2_Implementation", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash2___implementation.html", null ]
      ] ]
    ] ],
    [ "Data.HashFunction.IHashFunction_Extensions", "class_data_1_1_hash_function_1_1_i_hash_function___extensions.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_SpeedTest", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___speed_test.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< THashFunction >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IBlake3 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Blake3.Blake3_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake3_1_1_blake3___implementation___tests_1_1_i_hash_function___tests.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< ICityHash >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.CityHash.CityHash_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_city_hash___implementation___tests_1_1_i_hash_function___tests.html", null ],
      [ "Data.HashFunction.Test.CityHash.CityHash_Implementation_Tests.IHashFunction_Tests_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_city_hash___implementation___tests_1_1_i82eee0bb5373bf3d48030c994b854636.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IFarmHashFingerprint128 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint128_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint128___implementatio9645d7c4ed1296d8bebfcc4cd2243d57.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IFarmHashFingerprint32 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint32_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint32___implementation14fe9415ca0df8d8c46009da3c01895f.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IFarmHashFingerprint64 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.FarmHash.FarmHashFingerprint64_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_farm_hash_fingerprint64___implementation10488273fd0e7958ed99695658556211.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IHashAlgorithmWrapper >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests.IHashFunction_Tests_MD5", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementacc217851f5c869f280d516270b8edea8.html", null ],
      [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests.IHashFunction_Tests_SHA1", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementa70ca32e211a71089f6e333ba3876c89f.html", null ],
      [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests.IHashFunction_Tests_SHA256", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementaf843cd01b0c9e1d4a175a2b2e9c6ff21.html", null ],
      [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests.IHashFunction_Tests_SHA384", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementae7d17293e799b196b2bc3ab7411d1772.html", null ],
      [ "Data.HashFunction.Test.HashAlgorithm.HashAlgorithmWrapper_Implementation_Tests.IHashFunction_Tests_SHA512", "class_data_1_1_hash_function_1_1_test_1_1_hash_algorithm_1_1_hash_algorithm_wrapper___implementad9908f8db342ca1945e9ffb423bdabdc.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IJenkinsLookup3 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3___implementation___tests_1_1_i_hash_function___tests.html", null ],
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3_Implementation_Tests.IHashFunction_Tests_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3___implementation___tests_146a2898bf2f9e4c359395dacc8e94412.html", null ],
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3_Implementation_Tests.IHashFunction_Tests_WithInitVals", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3___implementation___tests_14ca0f41fea792f137a056917324bd557.html", null ],
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3_Implementation_Tests.IHashFunction_Tests_WithInitVals_DefaultHashSize", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3___implementation___tests_12208c0ee3dbe0e9d4290e05f8b392dce.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IMurmurHash1 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.MurmurHash.MurmurHash1_Implementation_Tests.IHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash1___implementation___tests_1_1_i_hash_function___tests.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< IMurmurHash2 >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.MurmurHash.MurmurHash2_Implementation_Tests.IHashFunction_Tests_MurmurHash2", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash2___implementation___tests_97ce3e048aa6a3925a87c7aa850176bf.html", null ],
      [ "Data.HashFunction.Test.MurmurHash.MurmurHash2_Implementation_Tests.IHashFunction_Tests_MurmurHash2_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash2___implementation___tests_35c8d2ff5df1f0a6c92e8af4ddd49d01.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< TStreamableHashFunction >", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< TStreamableHashFunction >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", null ]
    ] ],
    [ "Data.HashFunction.Jenkins.IJenkinsLookup2Config", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup2_config.html", [
      [ "Data.HashFunction.Jenkins.JenkinsLookup2Config", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup2_config.html", null ]
    ] ],
    [ "Data.HashFunction.Jenkins.IJenkinsLookup2Factory", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup2_factory.html", [
      [ "Data.HashFunction.Jenkins.JenkinsLookup2Factory", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup2_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Jenkins.IJenkinsLookup3Config", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup3_config.html", [
      [ "Data.HashFunction.Jenkins.JenkinsLookup3Config", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup3_config.html", null ]
    ] ],
    [ "Data.HashFunction.Jenkins.IJenkinsLookup3Factory", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_lookup3_factory.html", [
      [ "Data.HashFunction.Jenkins.JenkinsLookup3Factory", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_lookup3_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Jenkins.IJenkinsOneAtATimeFactory", "interface_data_1_1_hash_function_1_1_jenkins_1_1_i_jenkins_one_at_a_time_factory.html", [
      [ "Data.HashFunction.Jenkins.JenkinsOneAtATimeFactory", "class_data_1_1_hash_function_1_1_jenkins_1_1_jenkins_one_at_a_time_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MetroHash.IMetroHash128Factory", "interface_data_1_1_hash_function_1_1_metro_hash_1_1_i_metro_hash128_factory.html", [
      [ "Data.HashFunction.MetroHash.MetroHash128Factory", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash128_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MetroHash.IMetroHash64Factory", "interface_data_1_1_hash_function_1_1_metro_hash_1_1_i_metro_hash64_factory.html", [
      [ "Data.HashFunction.MetroHash.MetroHash64Factory", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash64_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MetroHash.IMetroHashConfig", "interface_data_1_1_hash_function_1_1_metro_hash_1_1_i_metro_hash_config.html", [
      [ "Data.HashFunction.MetroHash.MetroHashConfig", "class_data_1_1_hash_function_1_1_metro_hash_1_1_metro_hash_config.html", null ]
    ] ],
    [ "Data.HashFunction.BernsteinHash.IModifiedBernsteinHashFactory", "interface_data_1_1_hash_function_1_1_bernstein_hash_1_1_i_modified_bernstein_hash_factory.html", [
      [ "Data.HashFunction.BernsteinHash.ModifiedBernsteinHashFactory", "class_data_1_1_hash_function_1_1_bernstein_hash_1_1_modified_bernstein_hash_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash1Config", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash1_config.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash1Config", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash1_config.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash1Factory", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash1_factory.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash1Factory", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash1_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash2Config", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash2_config.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash2Config", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash2_config.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash2Factory", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash2_factory.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash2Factory", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash2_factory.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash3Config", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash3_config.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash3Config", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3_config.html", null ]
    ] ],
    [ "Data.HashFunction.MurmurHash.IMurmurHash3Factory", "interface_data_1_1_hash_function_1_1_murmur_hash_1_1_i_murmur_hash3_factory.html", [
      [ "Data.HashFunction.MurmurHash.MurmurHash3Factory", "class_data_1_1_hash_function_1_1_murmur_hash_1_1_murmur_hash3_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Pearson.IPearsonConfig", "interface_data_1_1_hash_function_1_1_pearson_1_1_i_pearson_config.html", [
      [ "Data.HashFunction.Pearson.PearsonConfig", "class_data_1_1_hash_function_1_1_pearson_1_1_pearson_config.html", null ],
      [ "Data.HashFunction.Pearson.WikipediaPearsonConfig", "class_data_1_1_hash_function_1_1_pearson_1_1_wikipedia_pearson_config.html", null ]
    ] ],
    [ "Data.HashFunction.Pearson.IPearsonFactory", "interface_data_1_1_hash_function_1_1_pearson_1_1_i_pearson_factory.html", [
      [ "Data.HashFunction.Pearson.PearsonFactory", "class_data_1_1_hash_function_1_1_pearson_1_1_pearson_factory.html", null ]
    ] ],
    [ "Data.HashFunction.SpookyHash.ISpookyHashConfig", "interface_data_1_1_hash_function_1_1_spooky_hash_1_1_i_spooky_hash_config.html", [
      [ "Data.HashFunction.SpookyHash.SpookyHashConfig", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_config.html", null ]
    ] ],
    [ "Data.HashFunction.SpookyHash.ISpookyHashV1Factory", "interface_data_1_1_hash_function_1_1_spooky_hash_1_1_i_spooky_hash_v1_factory.html", [
      [ "Data.HashFunction.SpookyHash.SpookyHashV1Factory", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v1_factory.html", null ]
    ] ],
    [ "Data.HashFunction.SpookyHash.ISpookyHashV2Factory", "interface_data_1_1_hash_function_1_1_spooky_hash_1_1_i_spooky_hash_v2_factory.html", [
      [ "Data.HashFunction.SpookyHash.SpookyHashV2Factory", "class_data_1_1_hash_function_1_1_spooky_hash_1_1_spooky_hash_v2_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IBernsteinHash >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.BernsteinHash.BernsteinHash_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_bernstein_hash___implementation___t5a50e4d5355987adb79ee9dedb252fc7.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IBlake2B >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_streamable_hash_function___tests.html", null ],
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests_CanonicalKeyed", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_stre1747189d9f5f031b2f8f80afc16d9c1.html", null ],
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests_CanonicalUnKeyed", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_strf409886b54a1b261535099576a771799.html", null ],
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_strd7b004ea444fb9ff130ffc7fc832db00.html", null ],
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests_WithHashSizeAndFoobarAsKey", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_str73691a32651f6953340efbd51d650519.html", null ],
      [ "Data.HashFunction.Test.Blake2.Blake2B_Implementation_Tests.IStreamableHashFunction_Tests_WithHashSizeAndFoobarAsKeySaltAndPersonalization", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_blake2_b___implementation___tests_1_1_i_str51809edf087a54b66d6e0de763a0310e.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IBuzHash >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.BuzHash.BuzHash_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash___implementation___tests_1_1_i_streamable_hash_function___tests.html", null ],
      [ "Data.HashFunction.Test.BuzHash.BuzHash_Implementation_Tests.IStreamableHashFunction_Tests_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash___implementation___tests_1_1_i_s39e975cf8ea528e8ea049d6503989016.html", null ],
      [ "Data.HashFunction.Test.BuzHash.BuzHash_Implementation_Tests.IStreamableHashFunction_Tests_RightShift", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash___implementation___tests_1_1_i_s2e2c127f1a1f0b797837945f6f8da322.html", null ],
      [ "Data.HashFunction.Test.BuzHash.BuzHash_Implementation_Tests.IStreamableHashFunction_Tests_RightShift_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_buz_hash_1_1_buz_hash___implementation___tests_1_1_i_s05824a66ff313a6ca314ea8f4aedfea0.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< ICRC >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_ARC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamad0035a3f342b1e880cb358c17ea89fda.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC10", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama48ae8b1cc309d9cb6390e6d1d0a7df53.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC10_CDMA2000", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama467bdf2e85aabca3f07e4ac45f7c378c.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC11", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama3758557c48a199648abff3a9e292613f.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC12_3GPP", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama2ecc98c4e0b846b7a4bc23004370ce8d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC12_CDMA2000", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama459ef091e3e03802005d67993dfff63e.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC12_DECT", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamae1b6c36383393db9b5088bde871ae214.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC13_BBC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama23e56cf430e4798d56ac5ea5af48d37a.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC14_DARC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama541ab230b136808d68a9da9eb4868d6d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC15", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama7d3d4ab5cb388102d050302930ed5269.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC15_MPT1327", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaf8320178a569944d31bb17f54263a945.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_AUGCCITT", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaebf85d6465fafe2748eed950ad1e4c35.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_BUYPASS", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamadd7335661759e5fb15aa62e955268591.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_CCITTFALSE", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaac45335a5d5f4d8fd65d459f3eccaac5.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_CDMA2000", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama639fb0bc7c6b8eaa1d35327693625e8b.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_DDS110", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama1d0959dde658ce379e7cdf085f68f0ba.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_DECTR", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama78922a22a52634e6555771f521779ed2.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_DECTX", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama6be6ff5f0019778f40307f74ce5c968d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_DNP", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama34e4519e8e0366291aa4afb95ab12db0.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_EN13757", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama9c4f47b8f8a1f9e9f26416a738252c0a.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_GENIBUS", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamadb2c75875701518bf6c575be47887dea.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_MAXIM", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama609c059c51ccc67de91195e32d69f0e8.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_MCRF4XX", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama6914980ddcc17ccc79683e712a248b3a.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_RIELLO", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama7669d34e082db11f759d505821426bca.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_T10DIF", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaa467a786dbfa77f0022f3d25bb3ab41f.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_TELEDISK", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama74d6809b2ca7293d037947352cd9cd38.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_TMS37157", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama0789f9b929bdac47060b683dd3891a74.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC16_USB", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamad7ddf063725120a96d36a53661d8c119.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC24", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama209d581e21ba8c83397e6e0d6fcd748f.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC24_FLEXRAYA", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama4428d3b56d0e81a1fde01d2fbdde6275.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC24_FLEXRAYB", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamadc5f45549cf52fb3535cb74bdb2b5b3c.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC31_PHILIPS", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamab980f469360454dc2bca02d79cd48d49.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama03e620303a2bf4028a8c04af83671ce7.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32C", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama5708543075a93a9ef7dd032fc0c2e31d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32D", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaee95101decb385d73fb069cd3a7f9181.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32Q", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama20f417428cd14b09e49aa46b6ae860c2.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32_BZIP2", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama6e45e526e536f2da03a7d9baab4d5d94.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32_MPEG2", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamafb613383e49515f2d4c2180e472560de.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC32_POSIX", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama3c288bdea23aad897c4f0b52f6c5bd5b.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC3_ROHC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama4924ae19ffc485ca49c40dd48f396c2e.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC40_GSM", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaee77816dcb747d6a8137eb4ac619ce5f.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC4_ITU", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama47655ace9247a2c97ba98aca8046d0b7.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC5_EPC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaec9e0b62abead5c5bbb220db02ee83ab.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC5_ITU", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama4e079d723ece036c26589a5daf093e1d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC5_USB", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama791034dbb35c3cc78598b767552691dd.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC64", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaf3897b054b205b04b77123265bd3da24.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC64_WE", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamabc03e31a6c64392ecf7cf374e5c0f8ce.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC64_XZ", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama6f81c2ad03290fa6f6d6586d54765363.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC6_CDMA2000A", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama02e0130ff59c1a09eb7be62cc878ca4d.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC6_CDMA2000B", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama02ca6d391349690a6a8ec3acc1fef2da.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC6_DARC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama374c75080ed6a3691f4c2a1924847796.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC6_ITU", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaefd4c422ece1a5e5eae689b6ce4460de.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC7", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaa6486a4b3d25a6e404a829974d0e91e5.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC7_ROHC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaa7132235a00da77662d4f272a5c5b464.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama81f12eee3688faf9e7225915807969b3.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_CDMA2000", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamadd8a3c38b1f6a7790ad1a6b001829eec.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_DARC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamafa87b66c1bb35e13cfe35c828019ec3f.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_DVBS2", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamad53848091cf32a5b87166f065c10f556.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_EBU", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama8f8de85c0c9803b133e12c85caa8df38.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_ICODE", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama9bfda3fb97cb81048a8ee68d51376de7.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_ITU", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama65a77be687d4199d636e6973256b515b.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_MAXIM", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama372a328d64c7063bc6d139a306c3b5bf.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_ROHC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaccda9bb0ebedec48aa4cee10c4701c90.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRC8_WCDMA", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama69cd46a0da2a71dda5e8057082762cc1.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_CRCA", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama4b714134fa537003059e9e7b3964a3a4.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_JAMCRC", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama53a4f3cd9a6ea7703507bd46ee42d89c.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_KERMIT", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streama71c6d4ad88f22db9c2930f7a84fe0f17.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_MODBUS", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamaf31357d5ee7c6a8d2abd4513dc2cfba8.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_X25", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamable_hash_function___tests___x25.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_XFER", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamad62655bcce70315b50722bbe3032204c.html", null ],
      [ "Data.HashFunction.Test.CRC.CRC_Implementation_Tests.IStreamableHashFunction_Tests_XMODEM", "class_data_1_1_hash_function_1_1_test_1_1_c_r_c_1_1_c_r_c___implementation___tests_1_1_i_streamab124f2feab8613062bfb1b52cdf59780.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IELF64 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.ELF64.ELF64_Implementation_Tests.IStreamableHashFunction_Tests_ELF64", "class_data_1_1_hash_function_1_1_test_1_1_e_l_f64_1_1_e_l_f64___implementation___tests_1_1_i_strb5d99049ab1c55ba94f6cb442ca71c86.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IFNV1 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.FNV.FNV1_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1___implementation___tests_1_1_i_streamable_hash_function___tests.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IFNV1a >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.FNV.FNV1a_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_f_n_v_1_1_f_n_v1a___implementation___tests_1_1_i_streamable_hash_function___tests.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IJenkinsLookup2 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup2_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup2___implementation___tests_1e1f38437db9355f635bff1654e1b7dd0.html", null ],
      [ "Data.HashFunction.Test.Jenkins.JenkinsLookup2_Implementation_Tests.IStreamableHashFunction_Tests_WithInitVal", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup2___implementation___tests_163b9660547b3802797b9a61fb6f09846.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IJenkinsOneAtATime >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Jenkins.JenkinsOneAtATime_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_one_at_a_time___implementation___tdadc9ace4753f43d7d8bbbef87464cb6.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IMetroHash128 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.MetroHash.MetroHash128_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash128___implementation___tests_88bb35e8f2be6b888aa34241a8f0b9b9.html", null ],
      [ "Data.HashFunction.Test.MetroHash.MetroHash128_Implementation_Tests.IStreamableHashFunction_Tests_WithSeed", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash128___implementation___tests_1aeecd35b7d8862b9d2c00044cb47a54.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IMetroHash64 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.MetroHash.MetroHash64_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash64___implementation___tests_181b9e600fede34ae10c7b64b51f95671.html", null ],
      [ "Data.HashFunction.Test.MetroHash.MetroHash64_Implementation_Tests.IStreamableHashFunction_Tests_WithSeed", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash64___implementation___tests_1a9b37612099253d460b277c39f39b70c.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IModifiedBernsteinHash >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHash_Implementation_Tests.IStreamableHashFunction_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implement5faf157baec7e0c60cad2009329a3807.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IMurmurHash3 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.MurmurHash.MurmurHash3_Implementation_Tests.IStreamableHashFunction_Tests_MurmurHash3", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash3___implementation___tests_e1b0cc7420353a0a9d5a2e705f60ba06.html", null ],
      [ "Data.HashFunction.Test.MurmurHash.MurmurHash3_Implementation_Tests.IStreamableHashFunction_Tests_MurmurHash3_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash3___implementation___tests_8aac40cef17de45dad896cb9cf506185.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IPearson >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.Pearson.Pearson_Implementation_Tests.IStreamableHashFunction_Tests_WikipediaPearson", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson___implementation___tests_1_1_i_str9f249415deb70da2b4e1f016dbe4e802.html", null ],
      [ "Data.HashFunction.Test.Pearson.Pearson_Implementation_Tests.IStreamableHashFunction_Tests_WikipediaPearson_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson___implementation___tests_1_1_i_str77723b1f69c5d26984328af85496101e.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< ISpookyHashV1 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV1", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1___implementation___testfb1f1b3cb8e70a9f63c898adc8672cbe.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV1_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1___implementation___test746d187e4b0107141938a225104e48a1.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV1_WithInitVals", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1___implementation___test74c9f77c561cd2b15b900fbbbd6848c1.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV1_WithInitVals_DefaultHashSize", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1___implementation___teste167bb36f07bf5968e0551ff1a620996.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< ISpookyHashV2 >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV2", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2___implementation___testccd3bc008f404dc9c93798aa9c9843cd.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV2_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2___implementation___testec40e9e7f37d18ca964f738f40c57ed8.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV2_WithInitVals", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2___implementation___test1423b20b836a6ea0c90e5e82a2b3fc66.html", null ],
      [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2_Implementation_Tests.IStreamableHashFunction_Tests_SpookyHashV2_WithInitVals_DefaultHashSize", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2___implementation___test00e02c02221b4219304c9323f1050ebe.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IStreamableHashFunction_TestBase< IxxHash >", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", [
      [ "Data.HashFunction.Test.xxHash.xxHash_Implementation_Tests.IStreamableHashFunction_Tests_xxHash", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash___implementation___tests_1_1_i_strea9ecb1c5afcdaee6b7c4624451129d1c5.html", null ],
      [ "Data.HashFunction.Test.xxHash.xxHash_Implementation_Tests.IStreamableHashFunction_Tests_xxHash_DefaultConstructor", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash___implementation___tests_1_1_i_strea6e3e44f6465d6ef746adb4382b71f073.html", null ],
      [ "Data.HashFunction.Test.xxHash.xxHash_Implementation_Tests.IStreamableHashFunction_Tests_xxHash_WithInitVal", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash___implementation___tests_1_1_i_strea41f3429c5bcfa46c72a477d0ce63d706.html", null ]
    ] ],
    [ "Data.HashFunction.xxHash.IxxHashConfig", "interface_data_1_1_hash_function_1_1xx_hash_1_1_ixx_hash_config.html", [
      [ "Data.HashFunction.xxHash.xxHashConfig", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash_config.html", null ]
    ] ],
    [ "Data.HashFunction.xxHash.IxxHashFactory", "interface_data_1_1_hash_function_1_1xx_hash_1_1_ixx_hash_factory.html", [
      [ "Data.HashFunction.xxHash.xxHashFactory", "class_data_1_1_hash_function_1_1xx_hash_1_1xx_hash_factory.html", null ]
    ] ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup2_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup2___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup2Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup2_config___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup2Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup2_factory___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3_config___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3_factory___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsLookup3Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_lookup3_tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsOneAtATime_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_one_at_a_time___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Jenkins.JenkinsOneAtATimeFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_jenkins_1_1_jenkins_one_at_a_time_factory___tests.html", null ],
    [ "Data.HashFunction.Core.LibraryLoader.Kernel32", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_kernel32.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_TestBase< THashFunction >.KnownValue", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base_1_1_known_value.html", null ],
    [ "Data.HashFunction.Core.LibraryLoader.Libdl", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_libdl.html", null ],
    [ "Data.HashFunction.Test.MetroHash.MetroHash128_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash128___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.MetroHash.MetroHash128Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash128_factory___tests.html", null ],
    [ "Data.HashFunction.Test.MetroHash.MetroHash64_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash64___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.MetroHash.MetroHash64Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash64_factory___tests.html", null ],
    [ "Data.HashFunction.Test.MetroHash.MetroHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_metro_hash_1_1_metro_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.BernsteinHash.ModifiedBernsteinHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_bernstein_hash_1_1_modified_bernstein_hash_factory___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash1_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash1___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash1Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash1_config___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash1Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash1_factory___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash2_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash2___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash2Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash2_config___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash2Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash2_factory___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash3_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash3___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash3Config_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash3_config___tests.html", null ],
    [ "Data.HashFunction.Test.MurmurHash.MurmurHash3Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_murmur_hash_1_1_murmur_hash3_factory___tests.html", null ],
    [ "Data.HashFunction.Core.LibraryLoader.OperatingSystemHelper", "class_data_1_1_hash_function_1_1_core_1_1_library_loader_1_1_operating_system_helper.html", null ],
    [ "Data.HashFunction.Test.Pearson.Pearson_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.Pearson.PearsonBaseTests", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson_base_tests.html", null ],
    [ "Data.HashFunction.Test.Pearson.PearsonConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson_config___tests.html", null ],
    [ "Data.HashFunction.Test.Pearson.PearsonFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_pearson_factory___tests.html", null ],
    [ "Data.HashFunction.Test.SpookyHash.SpookyHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.SpookyHash.SpookyHashV1Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v1_factory___tests.html", null ],
    [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.SpookyHash.SpookyHashV2Factory_Tests", "class_data_1_1_hash_function_1_1_test_1_1_spooky_hash_1_1_spooky_hash_v2_factory___tests.html", null ],
    [ "Stream", null, [
      [ "Data.HashFunction.Test._Mocks.SlowAsyncStream", "class_data_1_1_hash_function_1_1_test_1_1___mocks_1_1_slow_async_stream.html", null ]
    ] ],
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests.Sugar", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar.html", null ],
    [ "Data.HashFunction.Test.IHashFunction_Extensions_Tests.SugarWithDesiredSize", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests_1_1_sugar_with_desired_size.html", null ],
    [ "Data.HashFunction.Test._Utilities.TestConstants", "class_data_1_1_hash_function_1_1_test_1_1___utilities_1_1_test_constants.html", null ],
    [ "Data.HashFunction.Blake2.Utilities.UInt128", "struct_data_1_1_hash_function_1_1_blake2_1_1_utilities_1_1_u_int128.html", null ],
    [ "Data.HashFunction.CityHash.Utilities.UInt128", "struct_data_1_1_hash_function_1_1_city_hash_1_1_utilities_1_1_u_int128.html", null ],
    [ "Data.HashFunction.FarmHash.Utilities.UInt128", "struct_data_1_1_hash_function_1_1_farm_hash_1_1_utilities_1_1_u_int128.html", null ],
    [ "Data.HashFunction.Test.Blake2.Utilities.UInt128_Tests", "class_data_1_1_hash_function_1_1_test_1_1_blake2_1_1_utilities_1_1_u_int128___tests.html", null ],
    [ "Data.HashFunction.Test.CityHash.Utilities.UInt128_Tests", "class_data_1_1_hash_function_1_1_test_1_1_city_hash_1_1_utilities_1_1_u_int128___tests.html", null ],
    [ "Data.HashFunction.Test.FarmHash.Utilities.UInt128_Tests", "class_data_1_1_hash_function_1_1_test_1_1_farm_hash_1_1_utilities_1_1_u_int128___tests.html", null ],
    [ "Data.HashFunction.Test.Test._Utilities.UtilityExtension_Tests", "class_data_1_1_hash_function_1_1_test_1_1_test_1_1___utilities_1_1_utility_extension___tests.html", null ],
    [ "Data.HashFunction.Test._Utilities.UtilityExtensions", "class_data_1_1_hash_function_1_1_test_1_1___utilities_1_1_utility_extensions.html", null ],
    [ "Data.HashFunction.Test.Pearson.WikipediaPearsonConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1_pearson_1_1_wikipedia_pearson_config___tests.html", null ],
    [ "Data.HashFunction.Test.xxHash.xxHash_Implementation_Tests", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash___implementation___tests.html", null ],
    [ "Data.HashFunction.Test.xxHash.xxHashConfig_Tests", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash_config___tests.html", null ],
    [ "Data.HashFunction.Test.xxHash.xxHashFactory_Tests", "class_data_1_1_hash_function_1_1_test_1_1xx_hash_1_1xx_hash_factory___tests.html", null ]
];