var namespace_data_1_1_hash_function_1_1_test =
[
    [ "_Mocks", "namespace_data_1_1_hash_function_1_1_test_1_1___mocks.html", "namespace_data_1_1_hash_function_1_1_test_1_1___mocks" ],
    [ "_Utilities", "namespace_data_1_1_hash_function_1_1_test_1_1___utilities.html", "namespace_data_1_1_hash_function_1_1_test_1_1___utilities" ],
    [ "BernsteinHash", "namespace_data_1_1_hash_function_1_1_test_1_1_bernstein_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_bernstein_hash" ],
    [ "Blake2", "namespace_data_1_1_hash_function_1_1_test_1_1_blake2.html", "namespace_data_1_1_hash_function_1_1_test_1_1_blake2" ],
    [ "Blake3", "namespace_data_1_1_hash_function_1_1_test_1_1_blake3.html", "namespace_data_1_1_hash_function_1_1_test_1_1_blake3" ],
    [ "BuzHash", "namespace_data_1_1_hash_function_1_1_test_1_1_buz_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_buz_hash" ],
    [ "CityHash", "namespace_data_1_1_hash_function_1_1_test_1_1_city_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_city_hash" ],
    [ "Core", "namespace_data_1_1_hash_function_1_1_test_1_1_core.html", "namespace_data_1_1_hash_function_1_1_test_1_1_core" ],
    [ "CRC", "namespace_data_1_1_hash_function_1_1_test_1_1_c_r_c.html", "namespace_data_1_1_hash_function_1_1_test_1_1_c_r_c" ],
    [ "ELF64", "namespace_data_1_1_hash_function_1_1_test_1_1_e_l_f64.html", "namespace_data_1_1_hash_function_1_1_test_1_1_e_l_f64" ],
    [ "FarmHash", "namespace_data_1_1_hash_function_1_1_test_1_1_farm_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_farm_hash" ],
    [ "FNV", "namespace_data_1_1_hash_function_1_1_test_1_1_f_n_v.html", "namespace_data_1_1_hash_function_1_1_test_1_1_f_n_v" ],
    [ "HashAlgorithm", "namespace_data_1_1_hash_function_1_1_test_1_1_hash_algorithm.html", "namespace_data_1_1_hash_function_1_1_test_1_1_hash_algorithm" ],
    [ "Jenkins", "namespace_data_1_1_hash_function_1_1_test_1_1_jenkins.html", "namespace_data_1_1_hash_function_1_1_test_1_1_jenkins" ],
    [ "MetroHash", "namespace_data_1_1_hash_function_1_1_test_1_1_metro_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_metro_hash" ],
    [ "MurmurHash", "namespace_data_1_1_hash_function_1_1_test_1_1_murmur_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_murmur_hash" ],
    [ "Pearson", "namespace_data_1_1_hash_function_1_1_test_1_1_pearson.html", "namespace_data_1_1_hash_function_1_1_test_1_1_pearson" ],
    [ "SpookyHash", "namespace_data_1_1_hash_function_1_1_test_1_1_spooky_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1_spooky_hash" ],
    [ "Test", "namespace_data_1_1_hash_function_1_1_test_1_1_test.html", "namespace_data_1_1_hash_function_1_1_test_1_1_test" ],
    [ "xxHash", "namespace_data_1_1_hash_function_1_1_test_1_1xx_hash.html", "namespace_data_1_1_hash_function_1_1_test_1_1xx_hash" ],
    [ "IHashFunction_Extensions_Tests", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___extensions___tests" ],
    [ "IHashFunction_SpeedTest", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___speed_test.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___speed_test" ],
    [ "IHashFunction_TestBase", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base.html", "class_data_1_1_hash_function_1_1_test_1_1_i_hash_function___test_base" ],
    [ "IStreamableHashFunction_TestBase", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base.html", "class_data_1_1_hash_function_1_1_test_1_1_i_streamable_hash_function___test_base" ]
];